/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ConnectedUsersList: typeof import('./src/components/ConnectedUsersList.vue')['default']
    DayEvents: typeof import('./src/components/DayEvents.vue')['default']
    DaySketchPad: typeof import('./src/components/DaySketchPad.vue')['default']
    EventCalendar: typeof import('./src/components/EventCalendar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainCalendar: typeof import('./src/components/MainCalendar.vue')['default']
    PersonalCabinet: typeof import('./src/components/PersonalCabinet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningTimersPopup: typeof import('./src/components/RunningTimersPopup.vue')['default']
  }
}
